LICENSE = "MIT"

PACKAGE_ARCH = "${OSS_LAYER_ARCH}"
# Toolchain and native packages
DEPENDS = "libgcc glibc-locale gcc-runtime gcc-sanitizers gdb-cross-${TARGET_ARCH}"

DEPENDS+= "\
abseil-cpp-native \
acl-native \
apr-native \
attr-native \
autoconf-archive-native \
autoconf-native \
automake-native \
bc-native \
binutils-native \
bison-native \
boost-build-native \
breakpad-native \
bzip2-native \
ca-certificates-native \
c-ares-native \
cargo-native \
ccache-native \
cdrtools-native \
chrpath-native \
chrpath-replacement-native \
cmake-native \
coreutils-native \
cracklib-native \
cross-localedef-native \
curl-native \
db-native \
dbus-glib-native \
dbus-native \
debianutils-native \
docbook-xml-dtd4-native \
docbook-xsl-stylesheets-native \
doxygen-native \
dwarfsrcfiles-native \
e2fsprogs-native \
elfutils-native \
erofs-utils-native \
expat-native \
file-native \
flex-native \
gdbm-native \
gdk-pixbuf-native \
gettext-minimal-native \
gettext-native \
glib-2.0-native \
glslang-native \
gmp-native \
gnu-config-native \
gobject-introspection-native \
gperf-native \
groff-native \
grpc-native \
gtk-doc-native \
icu-native \
intltool-native \
itstool-native \
jsoncpp-native \
kern-tools-native \
kmod-native \
ldconfig-native \
libarchive-native \
libcap-native \
libcap-ng-native \
libedit-native \
libffi-native \
libgcrypt-native \
libgpg-error-native \
libical-native \
libjpeg-native \
libmpc-native \
libnsl2-native \
libpcre2-native \
libpcre-native \
libpng-native \
libsolv-native \
libssh2-native \
libtirpc-native \
libtool-native \
libxml2-native \
libxml-parser-perl-native \
libxslt-native \
libyaml-native \
lua-native \
lz4-native \
lzo-native \
lzop-native \
m4-native \
makedepend-native \
makedevs-native \
make-native \
meson-native \
mpfr-native \
nasm-native \
ncurses-native \
ninja-native \
nodejs-native \
nspr-native \
nss-native \
openssl-native \
opkg-native \
opkg-utils-native \
orc-native \
patchelf-native \
patch-native \
pbzip2-native \
perlcross-native \
perl-native \
pigz-native \
pkgconfig-native \
popt-native \
protobuf-c-native \
protobuf-native \
pseudo-native \
python-native \
python-lxml-native \
python-native \
python-setuptools-native \
python3-asn1crypto-native \
python3-certifi-native \
python3-cffi-native \
python3-cryptography-native \
python3-flit-core-native \
python3-idna-native \
python3-installer-native \
python3-jsonref-native \
python3-lxml-native \
python3-mako-native \
python3-native \
python3-packaging-native \
python3-pycparser-native \
python3-pyopenssl-native \
python3-pyparsing-native \
python3-semantic-version-native \
python3-setuptools-native \
python3-setuptools-rust-native \
python3-setuptools-scm-native \
python3-six-native \
python3-tomli-native \
python3-toml-native \
python3-typing-extensions-native \
python3-urllib3-native \
python3-wheel-native \
qemu-native \
quilt-native \
re2c-native \
re2-native \
readline-native \
rpm-native \
rsync-native \
ruby-native \
shadow-native \
shared-mime-info-native \
sqlite3-native \
squashfs-tools-native \
swig-native \
systemd-systemctl-native \
texinfo-dummy-native \
tzcode-native \
u-boot-tools-native \
unifdef-native \
unzip-native \
update-rc.d-native \
util-linux-libuuid-native \
util-linux-native \
util-macros-native \
vala-native \
wayland-native \
xmlto-native \
xorgproto-native \
xz-native \
zlib-native \
zstd-native \
"
DEPENDS += "\
rust-native \ 
rust-llvm-native \
cargo-native \
"
