# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-core/packagegroup-oss-docker.bb"

BBFILE_COLLECTIONS += "docker-generator"
BBFILE_PATTERN_docker-generator = "^${LAYERDIR}/"
BBFILE_PRIORITY_docker-generator = "6"

LAYERDEPENDS_docker-generator = "core"
LAYERSERIES_COMPAT_docker-generator = "dunfell kirkstone"

D_ARCH_VARIANT ?= "arm7a"

BBMULTICONFIG ?= "arm7ve arm64"

TMPDIR ?= "${TOPDIR}/tmp-${D_ARCH_VARIANT}"
BUILDHISTORY_DIR ?= "${TOPDIR}/buildhistory-${D_ARCH_VARIANT}"

GENERATE_NATIVE_PKG_PREBUILT = "1"
